# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &juuso 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
  - &darwin age1z2e5qzsg730g70vxanyyfm40fz42rvgydklce48r5lgra55re3esyr7dyz
  - &muro age1alaa93s5t2awzuthqpxxsen76dvgkujh05rgglnv4ked3cnj6p2s56nt4t
  - &starlabs age1nashp3arcwz7gg4wapuphlpuzq5u8q5059sz23kpyha9hesxe9ss3nzj2v
creation_rules:
  - path_regex: hosts/darwin/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *juuso
      age:
      - *darwin
  - path_regex: nixosConfigurations/muro/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *juuso
      age:
      - *muro
  - path_regex: nixosConfigurations/starlabs/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *juuso
      age:
      - *starlabs
