wireguard:
    ponkila.conf: ENC[AES256_GCM,data:G3pcJOqiSko7O5RGyzs1DZKsdyP5HylFQn3M/L2MUCb9+Wwvu1aCcDTGvBze7iKHscK2hKRsUPi5SKS2Fkh6PIV61yznF5jW2zT5wYmaZfIc6Y8J88+C+5fcTuHBPH6a4StlLjFvbR34UFgYKvj+eTH8weOsoGr5epDR907VrEahaLP27rZeEBVXBzHPxS2ZnCEEJrYBe3b/c6XWIAwmeVqWMfdtIz3s25/UzTI0Fny7h6pOlJ1jD9S0BMB685BtKAfzCwI386fzt3FePrBErXjeINyKAW9zWo+YEzpilg2oJL1FV4qdeaoYNm2cm7wPpjAUtJ49uFgZ+JlHfPNBhISKxxuQBWg0USQliisBIBlSqO1q8I3kXeaXLyi8zIOQfMwdw6JZH++wqs6X2S9FuUbwJ9CwIEcfr50V8zl2EjJ6vbHImDEiGv/7+hW77DUFa1wJ5coD7UhYgYkDtlPKmQJtW6dHnKNV2FzrH5o0KyqAkADqLchoI90szv3P3WruLrWmxAipYWXujPbPKIkcORYVLigoIAcM0P+iwKpO3+cAxP8440bxVBbj,iv:M1lcDJ0Xb1hMK1zyeYrtBCgZeRjBDnOUBe45hrK1pTs=,tag:QKufHH7Nk3NftwV6J22xYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z2e5qzsg730g70vxanyyfm40fz42rvgydklce48r5lgra55re3esyr7dyz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeVhNR1hQNHRUb0QvRjlw
            cjhPUDJwRXZHNnEyTVNDZFBQTkhiRy9MMzMwCjlXRjBJcWZWaCsvVEpFNjdGOUR2
            OG9BOHg0Wm02UUpXVjJTdEU0RnpDYVEKLS0tIFBqUjBqVHlEcUJYVVBHNS9qYWFl
            S3V1aVN5b25SVk5wY2ptUzZVNm9nODgK2fsWA+COOaOcpeDOLEuGxgjiT9bTyU45
            2opythStSpVeeJISZsUlzAv9+p5Fd5mbqyf87u2xLPkraCchCu5FHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T21:50:40Z"
    mac: ENC[AES256_GCM,data:e7QB46E8HxE3rF/0iIb0n2YXOp3mTwYP7y22Nfo6TcwYm/4GLc8peknB5LGf48kYZBiFAy9KDjI/Bz7t6lPj7gMANHYy98yE18cEQHBzhP/hM29fYFCMTf7iJkdIuh5loAEswoeyfu5UMsXQmqfMjIIpFJIB9mzy15J7n417bqc=,iv:xwtVxe+3uVHqq23o1p5m5mh/qwCG+y8sz9YZeSlf8cM=,tag:+TtKxVtc+qiGgptqm/G4/Q==,type:str]
    pgp:
        - created_at: "2023-04-25T21:47:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hH4DfXeKk69lOL0SAgME37BfFSuI9l0cR14peWDqbhZNWn/tq1pMbOizs/WqffTl
            9S21rVdZ17cmkAlyL+1/ImIoswMFXNkdNYN+Mv1jWzBV5aAiRu3EkBO29NFgI6J5
            xgI6kPgdiM0UAjgjsIPAQ76h1LZRHi6SDUNnhvfAJ3nSXgF1py4jx0PyGuWuh1r4
            GZrtKlmTSG87Lyop6jFFKKgxTNOQlLltYb58mowtx2c12C60wf45c8dmV50X53pK
            6pxD1vgHCG2MGF7uEjZ1Z27AF6y/8KbV49hUdnYj+Gc=
            =v8cy
            -----END PGP MESSAGE-----
          fp: 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
