git:
    sendemail: ENC[AES256_GCM,data:fDOSyCEHYwjZ4F+6kk3CBSf0KX2m92rR/bssC4tXaMORzA/BQedjGfOlKZXraHHuj1pgB5t2pSYh7Uil/MIt1F8HIgwj380vr4xC7WUqIQIQ3mrlSezc8DTL1BelmievZArp/kcEquvJBlJPS7aTMaUdnlWHGB97N3r7JrwJq0pAHTCCLLwPyR/nSDIkGb42G6I503sohcoqxVVdv9pkxIFm+YptYvUz+o0=,iv:wv8Foxbvu3+Bf9rvz3iGzEP2pJWeO4wSke835VRk5o0=,tag:PRZEUzNQDmjHTk0TlP8ogQ==,type:str]
wireguard:
    ponkila.conf: ENC[AES256_GCM,data:0rnnt5+Cw4UpQ7DhcJGOHCSkQAy8qJQtwdM8ZVq0Ax5dSeU21DimFk/b2jfnPxADBKSJsWaYebFsCLKSbcz7MD+YpXkAHKBMdHD+0TbtuKoEkQHEDWxNCf9ok8gD2H8V1OXMevlbragtTkMHuvra+ExUSPBnoeeJSV//FXCSrFoccSgLjZRYnPBSXrUEmZpWOvyoTSnwAOswJj27qFYWVV2upI4hH6dKLqOgNHgDfX57voRnBrgJMpWU5uqkniS2tIBFUabjzk4FZBhHLh0KaGFdHO+J/oyH/IqQamsvdFVRKR7FncgUkChStk5b45pEu3uQx1BkmjeYrQZFMDqw1PsiIDsBflm7wJPAo8zPjyZz08vpYe1X9i1HaGDns8QGcpseRLv959f7pIYz5XReHEOMV+d+9QARXiDsx2ah+OKWGlB9o/Cf/nvkR+lgDGGBcEBMwixhWepdL0kgChnFYqyYKG+IOtFQeqNPDJpOB/enLU4pPpLIdlPlcIx3N8fam6ClXIeetbRpgWLthAJvG9r8Pc6wEA==,iv:tzK9SE/GfJc3FMTu7iTq0vrnQGoN0ZdinLXUwcQi7dA=,tag:gvPk0/WijHxYSwrJE2fk9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-13T14:03:04Z"
    mac: ENC[AES256_GCM,data:8QPtBN1P0FqmSP6RVevpiS7CFhL5a9hwQjpsqHSAKvd0Qp7Rwt4255IqqFLmH2HBCDhKyfD/fh31NXnMhNugNE8r/VDU+ygQDx8Y8B0Yk/h+WD9pXwFepw09EVNi9t8Uxk+aS4aBgLB3k0ktS8dKbJF3RT5BY455Ogd6grZZ9Jo=,iv:Wn+NyFylmZC35IgbH9sYGEAMY8J3PCxrEOHEhI71CTA=,tag:dwgb8YaD95m7PzY25nE5nQ==,type:str]
    pgp:
        - created_at: "2023-04-09T17:49:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hH4DfXeKk69lOL0SAgMEgmkIIiMqhlo3+sF36wP8HNiyRuBdyl11UoQS9aoSbqDY
            NPKaWd+XWpLROJH3cLQ0RtWvTfYBrH/Mz+xj4Bv+OzCA8f9BWAqgjX+frx9IEhWt
            762QiL5qXzS8LHeVIQke3je1VtIiczLTZRsDx4dQn/3SXAE+DiA0TEeXN7pmcFE3
            3EMkUL3D446f6j66FOhk7g8GYkR/fle9PNa8A48X7Y78tOgEB9YPtcsbRrpXeR3C
            MZEfNbHTCfcgjdzI2Deo2OQcH4PyFX9Dx5chMQqV
            =RkxZ
            -----END PGP MESSAGE-----
          fp: 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
