[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"

[project]
name = "age_plugin_fido2_hmac"
version = "0.1.0"
dependencies = [
  "cryptography~=41.0",
  "bech32~=1.2",
  "fido2~=1.1",
  "click~=8.1"
]
