mbsync:
    ponkila: ENC[AES256_GCM,data:m5v5OOffIXM2VWV/aiOKCSTMiT0=,iv:ErNQ1257h1hQ0HDmpuKbLrOIjq7AJGRr7GQ2UY4EPG4=,tag:9khveEma1oilxuRYg7XU9g==,type:str]
    mail.com: ENC[AES256_GCM,data:YqgvMPCSmK89xdC/7zC/7W5sTtI=,iv:LkuX51ch0/INwRm88oLZ/PyzhDnkWZUwJWrgyW37cys=,tag:CK3eUUVy7EIYRuSu6hvmCQ==,type:str]
    gmail: ENC[AES256_GCM,data:b4i9rT7UxHQ8mbTzB9RZqvfjLQ==,iv:Wk3WHK9LE7iGfTYcFlk9la8Dc2P9gO1NnJWxxMMrHt8=,tag:WQj5B7bsvMaqeqB/iJl9VA==,type:str]
    oxford: ENC[AES256_GCM,data:vSumJjVkw5mNA0EQl3O85Jub/WY=,iv:HvpuU6Bf0qFH/N2/VVuaPcP45rW2PtceONaH9aV9YAg=,tag:1aiT8XwfPNF6Xansm3y/Uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nashp3arcwz7gg4wapuphlpuzq5u8q5059sz23kpyha9hesxe9ss3nzj2v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMamdURDBPeTdQMU9UL2pC
            eHdwSmc2V1pUdW5HZDEreG5ONEpueWh2cW1BClkzTG9kSTRrQUNvUlp3QnhlYzND
            MDFPaEtpUUFORXZrUU1VSHp6MmVsV1UKLS0tIDI4KzBKT0RPdjgyYUx1aFRRQ0ps
            MnU1emFDVFRuYzBRZFk5V0g4K0VpZk0Kk4jsga+O/jDv9s1BcbLzuRvT54fK2/hG
            1Wdh7ftUeR7l2jK/7AiB3MuszYAX/LhtEJqWMdSRTp+uR7Bn6G1uXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-11T21:33:54Z"
    mac: ENC[AES256_GCM,data:DONHSIa5V41+8UsfffUGHcj11mW53xpK6pAK0rYttucdPWzlJSWDhB8ydg1xVrsqECAu+lOw0p8LhzkaW2wmdEWn1tGc+ODq/eKtScoPfGypBdKoOGsDPRtxzhJe5lOYyPjRt5SnMXZOND1OHZ3lwfkyW4miDXRxGRQajAJfDgM=,iv:Qrl3XGMCV4/12UyV+MB4POwAI95+s6Sf6fx4pkJUb1A=,tag:0VrRjIoo8geHmb3CmgvzLw==,type:str]
    pgp:
        - created_at: "2024-01-11T21:33:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4DfXeKk69lOL0SAgME1QUyXAT4jMkwep7JXHgWvX+FOEMMTlPf64VleDtePAQv
            7aI/3ciQCACK6eUeOD3PRkl3ex8KdRyiUw9gkF8kpjDLgx3M7SNplIoTDu8T+7yR
            lvgpxSg05/v371UOUYkihJXwm2gEZf6DRAHofCUb3N3SXgHQl0tjUsy1G/feKPwF
            T/axaciH6gmTBLiVGdKiPEvvQ2AEJsBRlW3c+vOJ6yyDVlTqtMleyKZOTWbaHob7
            LjLRZo939svxnC+c1rpGCraf6R1xCy/W5CnwlvO+D4E=
            =PmKs
            -----END PGP MESSAGE-----
          fp: 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
    unencrypted_suffix: _unencrypted
    version: 3.8.1
