frigate:
    piha: ENC[AES256_GCM,data:/YkoNW8uONVzCZeFKeENhutgcdYyKjBezvXeuZBk1qrmtkv9VyhWBFVW/7ZWqjhl3RcMrr52,iv:p3wMUWz9Oqjin/BppPPF8XN/7bwGGw30ZFWSl/X73W8=,tag:Wv+qQQxomk7qBoYuuevv+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1alaa93s5t2awzuthqpxxsen76dvgkujh05rgglnv4ked3cnj6p2s56nt4t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBublYwNlhHdWtaWTFRQkVU
            UHBEazNSaTZWWUVnN2hqV2h4SUNwZXdZeHpjCmFwUW5DaThPcFN4bjdMcTJySlZL
            R1k2bnZYYXp1eC8rTjZ6bEQzSmtRcVkKLS0tIDRTTUNTSHhtMlo3SW1qemdPMmkv
            cnBJOThjOU12MldheHdiR1hYT1BHSDgK+SmkEreGC9ArhqlWIxfO04XuVYavLjhR
            pW1/wmAH0RypfKEU9XZdhIiUf0IiVN/OKKRECwRtVL1sjAhDx+O55g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-11T16:38:10Z"
    mac: ENC[AES256_GCM,data:xDmQtWqxZtIiJkaqLIZLtMyR5mv5Fr/OI5SIRubKJ1QaSebIKSgl5pdbsHe+/wyxQ7qKFSZS6QKL+6C3hflYjWsIT07QmVygoon6OfrpzoCQUnrx2rHsOiGEuKQr3zGOyg9NFnhPQvLfsWg3GN5D819z88wYuFGJF4q+wWDrT7U=,iv:66sfhrNOquFu28Wi59RTIhl4xpitAEemebqghWJdM4I=,tag:r/fusZdYX8Mwc3JSXCG5fg==,type:str]
    pgp:
        - created_at: "2024-01-11T16:36:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4DfXeKk69lOL0SAgMEGiU2CzehH93qm8/0AdHBqRf8Gq6N+zaRBiX5r/jVl6nd
            ShEAvzbhlGnHWj2i5O/9q56VhoTnBX+u4+8EoI1/MjBCMxQtXG6TgWD+CrZwrDUQ
            Kdwivlm8TcTEjrLyHobjc3ZCDPdo5eA6mE9ItH/oXsXSXgGOZqFHSHL6YRVX3A1M
            x9NB2feSx90BxVfjw0bWo2Untn6QW3oCTafUKYRy1q6lOvyJ2NbRKhaIG8FiIfAF
            hD5FtX4zKdqBYuTparTpqniQLS9aHOGa/Om+rS/GnD0=
            =5yK9
            -----END PGP MESSAGE-----
          fp: 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
    unencrypted_suffix: _unencrypted
    version: 3.8.1
