frigate:
    piha: ENC[AES256_GCM,data:/YkoNW8uONVzCZeFKeENhutgcdYyKjBezvXeuZBk1qrmtkv9VyhWBFVW/7ZWqjhl3RcMrr52,iv:p3wMUWz9Oqjin/BppPPF8XN/7bwGGw30ZFWSl/X73W8=,tag:Wv+qQQxomk7qBoYuuevv+A==,type:str]
mbsync:
    ponkila: ENC[AES256_GCM,data:YVMhgvJLgOghKAqwiBpO9kREOww=,iv:EjGLpGS2d2ibhqkMDGki0pKfNBHFi61DdgxvPv+2Mks=,tag:htvNykaOGhVvGEECKGqOoA==,type:str]
    mail.com: ENC[AES256_GCM,data:eFV+128lht5egLcnJANdxYEHuDA=,iv:+NDnEIKx8I0b7XseCva6ySgBYbgyOJBMYcn/Z9QiLAg=,tag:TfhxNay/612VNrJ3jSUONw==,type:str]
    gmail: ENC[AES256_GCM,data:HWoYcIK9cVdYJ8heAHmdzREQsQ==,iv:93tKxlG9fcWeOuyFZwUvDLaaK+NrqLG5bVHC3oq2Pjs=,tag:bm/itvAX0oq4VEq47XFydQ==,type:str]
    oxford: ENC[AES256_GCM,data:P28BTkiWACrWJnak0LB7khbBgXc=,iv:GINv4m9bYTGY7Em5Mez2g/WCiCfM2uDJZVkI4VN3rJw=,tag:WxTMfVrygGyCA4FHjgqHYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1alaa93s5t2awzuthqpxxsen76dvgkujh05rgglnv4ked3cnj6p2s56nt4t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBublYwNlhHdWtaWTFRQkVU
            UHBEazNSaTZWWUVnN2hqV2h4SUNwZXdZeHpjCmFwUW5DaThPcFN4bjdMcTJySlZL
            R1k2bnZYYXp1eC8rTjZ6bEQzSmtRcVkKLS0tIDRTTUNTSHhtMlo3SW1qemdPMmkv
            cnBJOThjOU12MldheHdiR1hYT1BHSDgK+SmkEreGC9ArhqlWIxfO04XuVYavLjhR
            pW1/wmAH0RypfKEU9XZdhIiUf0IiVN/OKKRECwRtVL1sjAhDx+O55g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-11T20:24:55Z"
    mac: ENC[AES256_GCM,data:78st+dTaMzv1QPSZRnFLYI8ZVkV6Um98fa9G9EfSPU4COr9PXyfkTdz2EWdh+Neex1LFzZgdWDHuaLANQCTe7CgiyOxYtRVAbz09XRTbM4Zg5a5AxYLcuBn6Ez8g4WWSaXcjeUc97tqAzJNdBz0LQDziDErj2uz2fJVywj/+vEc=,iv:BSGgYZ5GFp6Ks4ckBldW2KN+WZ/TmtaYz5Al8Ht7sqI=,tag:ZPh7/9b7tFZiyrquDiUbGg==,type:str]
    pgp:
        - created_at: "2024-01-11T16:36:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4DfXeKk69lOL0SAgMEGiU2CzehH93qm8/0AdHBqRf8Gq6N+zaRBiX5r/jVl6nd
            ShEAvzbhlGnHWj2i5O/9q56VhoTnBX+u4+8EoI1/MjBCMxQtXG6TgWD+CrZwrDUQ
            Kdwivlm8TcTEjrLyHobjc3ZCDPdo5eA6mE9ItH/oXsXSXgGOZqFHSHL6YRVX3A1M
            x9NB2feSx90BxVfjw0bWo2Untn6QW3oCTafUKYRy1q6lOvyJ2NbRKhaIG8FiIfAF
            hD5FtX4zKdqBYuTparTpqniQLS9aHOGa/Om+rS/GnD0=
            =5yK9
            -----END PGP MESSAGE-----
          fp: 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
    unencrypted_suffix: _unencrypted
    version: 3.8.1
